### PR TITLE
Use Java 22 in the tests so that the javac fragment loads

### PR DESCRIPTION
**Pull request by datho7561**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Wouldn't it make sense to try to contribute it upstream first?

**Comment by datho7561** [comment]
I replicated these changes locally on the `dom-with-javac` branch. I was expecting there to be many failures due to using the JavacCompilationUnitResolver. However, there were only a few (7 failures, 1 error), which I think are probably the ones from the dom-based-operations branch. Something is missing from this PR in order to get it to work, and I have no idea what it is.

**Comment by datho7561** [comment]
Where would I contribute this upstream? This is for testing javac

**Comment by mickaelistria** [comment]
Adding the profiles to test with java 22 can be useful for JDT in general and doesn't depend on JDT, so it might be interesting to push it upstream and then we fetch it (only the github action will have to be updated in this branch)

**Comment by datho7561** [comment]
It seems like they already exist upstream, and have for over a month. I guess we need to rebase

**Comment by mickaelistria** [comment]
I rebased earlier today.

**Comment by datho7561** [comment]
The key to loading the javac fragment was that you needed to add it to the pom for the test bundle, so it wasn't just Java 22 that was needed.

**Pull request closed without merging**
