### PR TITLE
Revert "Ensure all parent nodes fully encompass their child nodes"

### PR DESCRIPTION
**Pull request by robstryker**
This reverts commit dd17d97223cf005373b6d60ec8a07c065edebb4e.

### CODE REVIEW

**Comment by mickaelistria** [comment]
Reverting this seems to make 26 tests back to success. I think we can revert it and get back to it later without loosing too much info here.

**Comment by mickaelistria** [comment]
Compared to closest build https://ci.eclipse.org/ls/job/jdt-core-incubator/job/dom-with-javac/697/ , this one fixes
```
$ curl -H 'Cache-Control: no-cache' --compressed https://ci.eclipse.org/ls/job/jdt-core-incubator/job/PR-1043/lastSuccessfulBuild/testReport/api/xml | xmllint --xpath '/testResult/suite/case[status != "PASSED" and status != "FIXED"]/*[name() = "className" $ curl -H 'Cache-Control: no-cache' --compressed https://ci.eclipse.org/ls/job/jdt-core-incubator/job/dom-with-javac/697/testReport/api/xml | xmllint --xpath '/testResult/suite/case[status != "PASSED" and status != "FIXED"]/*[name() = "className" or name() = "name"]/text()' - | sed 'N; s/\n/ /' - | sort > 697.txt
$ curl -H 'Cache-Control: no-cache' --compressed https://ci.eclipse.org/ls/job/jdt-core-incubator/job/PR-1043/lastSuccessfulBuild/testReport/api/xml | xmllint --xpath '/testResult/suite/case[status != "PASSED" and status != "FIXED"]/*[name() = "className" $ curl -H 'Cache-Control: no-cache' --compressed https://ci.eclipse.org/ls/job/jdt-core-incubator/job/PR-1043/lastSuccessfulBuild/testReport/api/xml | xmllint --xpath '/testResult/suite/case[status != "PASSED" and status != "FIXED"]/*[name() = "className" or name() = "name"]/text()' - | sed 'N; s/\n/ /' - | sort > 697.txt
$ diff pr.txt 697.txt | grep '>'
> org.eclipse.jdt.core.tests.dom.ASTConverter18Test test0009
> org.eclipse.jdt.core.tests.dom.ASTConverter18Test test0011
> org.eclipse.jdt.core.tests.dom.ASTConverter18Test testBug424138_002
> org.eclipse.jdt.core.tests.dom.ASTConverterAST3Test test0008
> org.eclipse.jdt.core.tests.dom.ASTConverterAST3Test test0009
> org.eclipse.jdt.core.tests.dom.ASTConverterAST3Test test0012
> org.eclipse.jdt.core.tests.dom.ASTConverterAST3Test test0090
> org.eclipse.jdt.core.tests.dom.ASTConverterAST3Test test0321
> org.eclipse.jdt.core.tests.dom.ASTConverterAST3Test test0337
> org.eclipse.jdt.core.tests.dom.ASTConverterAST4Test test0008
> org.eclipse.jdt.core.tests.dom.ASTConverterAST4Test test0009
> org.eclipse.jdt.core.tests.dom.ASTConverterAST4Test test0012
> org.eclipse.jdt.core.tests.dom.ASTConverterAST4Test test0090
> org.eclipse.jdt.core.tests.dom.ASTConverterAST4Test test0321
> org.eclipse.jdt.core.tests.dom.ASTConverterAST4Test test0337
> org.eclipse.jdt.core.tests.dom.ASTConverterAST8Test test0008
> org.eclipse.jdt.core.tests.dom.ASTConverterAST8Test test0009
> org.eclipse.jdt.core.tests.dom.ASTConverterAST8Test test0012
> org.eclipse.jdt.core.tests.dom.ASTConverterAST8Test test0090
> org.eclipse.jdt.core.tests.dom.ASTConverterAST8Test test0337
> org.eclipse.jdt.core.tests.dom.ASTConverterRecoveryTest testGH3155
> org.eclipse.jdt.core.tests.dom.ASTConverterTest test0008
> org.eclipse.jdt.core.tests.dom.ASTConverterTest test0009
> org.eclipse.jdt.core.tests.dom.ASTConverterTest test0012
> org.eclipse.jdt.core.tests.dom.ASTConverterTest test0090
> org.eclipse.jdt.core.tests.dom.ASTConverterTest test0321
> org.eclipse.jdt.core.tests.dom.ASTConverterTest test0337
> org.eclipse.jdt.core.tests.dom.TypeAnnotationsConverterTest test0004
> org.eclipse.jdt.core.tests.dom.TypeAnnotationsConverterTest test0005
> org.eclipse.jdt.core.tests.dom.TypeAnnotationsConverterTest test0006
> org.eclipse.jdt.core.tests.dom.TypeAnnotationsConverterTest test0007
> org.eclipse.jdt.core.tests.dom.TypeAnnotationsConverterTest test0008
> org.eclipse.jdt.core.tests.model.ClasspathTests testBug305122
```

**Comment by mickaelistria** [comment]
I don't think we should revert it, most new failures do highlight actual issues that are "just" made visible now with this good change.
For example, https://github.com/mickaelistria/eclipse.jdt.core/pull/new/arrayInitializerPosition https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/1054 is supposed to fix a bunch of tests by actually fixing a non-related bug too that was hidden so far.

**Comment by robstryker** [comment]
Yeah that's my analysis too.

**Pull request closed without merging**
