### PR TITLE
[WIP] [javac] adjust diagnostic range for error targetting method

### LINKED ISSUE #313: [javac] adjust diagnostic range for error targetting method
As an example, if you write a method with a return type specified and don't return anything, the entire block is highlighted:

image

I think we should match the behaviour of highlighting just the name of the method, in this case `myMethod`

### PR DESCRIPTION
**Pull request by snjeza**
Fixes #313

### CODE REVIEW

**Review by datho7561 — APPROVED** [review]
Seems good to me. I tried to think up other errors/warnings that should be labelled on the method name, but I could only think of missing return.

**Comment by filippor** [comment]
> Seems good to me. I tried to think up other errors/warnings that should be labelled on the method name, but I could only think of missing return.

the problem with contract es @Override missing super type non compatiple override and duplicate method

**Comment by mickaelistria** [comment]
I think that's a lot of code for a particular case and hope we can find more concise & generic way to handle those. In the meantime, this code does already improve things, so let's merge.

**Comment by mickaelistria** [comment]
Can you please rebase first?

**Comment by datho7561** [comment]
> the problem with contract es @OverRide missing super type non compatiple override and duplicate method

You're right, if you overload a method with the same parameters but different return type:

```java
public String aaa() {
	return "I am the real method";
}
public void aaa() {
	System.out.println("no, listen to me i am the real method");
}
```

Then the `aaa` is marked instead of the whole `aaa()`. Although I think the difference doesn't really matter to the end user, we might need to do this if we want the tests to pass. @snjeza do you think this is worth addressing in this PR?

**Comment by snjeza** [comment]
> do you think this is worth addressing in this PR?

I will try.

**Pull request merged**
