### PR TITLE
Don't adjust cursor offset when finding node to complete

### PR DESCRIPTION
**Pull request by datho7561**

### CODE REVIEW

**Comment by datho7561** [comment]
Should net 1 new passed test case

**Comment by mickaelistria** [comment]
No change in test count.

**Comment by mickaelistria** [comment]
However, it doesn't harm either, so let's merge.

**Comment by mickaelistria** [comment]
I think I found a case where this condition is useful: CompletionContextTests.test0084
```java
package test0084;
import 
public class X {
}
```
And then computing after `import `. The current DOMCompletionEngine takes the whole CompilationUnit as contextual node. In this case, it seems fine to consume earlier whitespace to resolve to the ImportDeclaration.

I'm not sure about the actual conditions yet, but I think it could be valid to consume the prefixing whitespaces if the previous node is not a SimpleName.

**Pull request merged**
