### PR TITLE
Actually fix lemminx compilation

### PR DESCRIPTION
**Pull request by datho7561**
Need to actually generate the `.class` files when building, since the `src/main/test` compilation needs the `.class` from `src/main/java` being present.

### CODE REVIEW

**Comment by datho7561** [comment]
@testforstephen if you have some time, I would appreciate if you could review this change. I don't fully understand why the .class files were being generated in a temporary folder instead of the expected folder. When I debugged the JavaBuilder running with ECJ, the .class files for the source files were generated and placed in `target` by the BatchImageBuilder.

**Comment by datho7561** [comment]
~~I ran the quick fix test suite from jdt.ui on this PR and this PR causes a bunch of errors. I'll look into fixing those.~~ seems to be a fluke, the test suite is flaky

**Comment by testforstephen** [comment]
> @testforstephen if you have some time, I would appreciate if you could review this change. I don't fully understand why the .class files were being generated in a temporary folder instead of the expected folder. When I debugged the JavaBuilder running with ECJ, the .class files for the source files were generated and placed in `target` by the BatchImageBuilder.

Javac generates .class files in a temporary folder because the JDT builder API expects the compiler to return class bytes rather than writing the files directly. To meet this requirement, we work around the javac implementation by generating .class files in a temporary directory first, then return the bytes of the temp class file to the ImageBuilder via the CompilationResult. Once the upstream ImageBuilder accepts the CompilationResult, we will delete the temp Javac class files. You can find the full discussion history in https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/535#issuecomment-2210460632.

**Comment by testforstephen** [comment]
I tried lemminx project with Javac bits, it can generate classes and test-classes under target directory successfully. Could you clarify the specific issue you encountered that you intend to address with this PR?

**Comment by datho7561** [comment]
If you clean the project, (eg. delete all the .class files under `target`) and rebuild, then many of the test files won't be able to compile, since compiling them relies on referencing the compiled source files, which aren't generated when the compilation of the test files starts.

**Comment by testforstephen** [comment]
> If you clean the project, (eg. delete all the .class files under `target`) and rebuild, then many of the test files won't be able to compile, since compiling them relies on referencing the compiled source files, which aren't generated when the compilation of the test files starts.

After deleting the `target` directory manually, I use `"Force Java Compilation -> Full"` command to perform a full build, it can regenerate all class files. In current implementation, we only persist class files for the requested ICompilationUnits in the compile operation. For those intermediate dependency sources, we don't persist class files for them. this is by design.

**Comment by datho7561** [comment]
Okay, I checked again, and compiling lemminx now works properly.

Some of the changes in this PR were related to compiling modules properly; I'll check if they are still necessary and move them over to a new PR.

**Pull request closed without merging**
