### PR TITLE
Extract `IBinding createBinding(String key)` into interface

### PR DESCRIPTION
**Pull request by datho7561**
Fix some tests that rely on using this interface.

See eclipse-jdtls/eclipse.jdt.javac#63

### CODE REVIEW

**Comment by mickaelistria** [comment]
Wouldn't it be simpler and consistent enough to add this method into the ICompilationUnitResolver interface?

**Comment by datho7561** [comment]
No, unfortunately. This is because the ECJ `ICompilationUnitResolver` facade is currently a static class, and `createBinding` in `CompilationUnitResolver` is non-static .

The two methods I see to work around this are to make the facade non-static, or make a separate interface for just `createBinding`. I don't know which is better, so I went with the second one. Maybe there is a different or better way.

**Comment by datho7561** [comment]
Okay, both `testBug212100a` and `testBug212100b` should be passing now.

There will be more errors; getting these bindings switch some failures over to errors; however the total number of failures+errors should have decreased.

**Comment by datho7561** [comment]
@mickaelistria if you have a better idea for how to structure this code, please let me know. For now, I've cleaned up the code, and made sure this actually makes some tests pass (there are 6 less failures it seems).

**Comment by mickaelistria** [comment]
Can you please rebase to facilitate review?

**Comment by datho7561** [comment]
Yep, I've rebased

**Comment by mickaelistria** [comment]
This is pretty good and it fixes some tests. Let's merge.
Can you please submit a PR to upstream JDT for those changes in jdt.core?

**Pull request merged**
