### PR TITLE
Fix/workaround bindings for generics vs parameterized

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
New failures are caused by generic and parameterized sharing the same `getKey()`, while generic should only show the type parameter simple name in `getKey` and parameterized should show the qualified name of the type parameter (including defining class prefix).

**Comment by robstryker** [comment]
Right now the field in question (isDeclaration) is kinda insufficient.  For example, a line of code that reads 

`if( myvar instanceof SomeType)`, SomeType is not a declaration, but it also is not related to a specific instance of SomeType, and so it must have a `getName()` that does not include any parameters or generics at all. 

There's a lot of code here inter-relating with each other and it's hard to keep track of it all.

**Comment by robstryker** [comment]
Please don't merge or continue working on this. I have overlapping code that I'd been working on for two days. Next time just ping me to point to the specific test and we can discuss.

**Comment by mickaelistria** [comment]
I've seen some of your commits are contributing big parts of necessary fixes and cherry-picked some of them. But I'm going to continue working on this as I believe the current proposal fixes more things in a more reliable way.

**Comment by mickaelistria** [comment]
This was updated after recent merge and this now shows a dozen of fixed tests compared to the "best" former state.

**Pull request merged**
