### PR TITLE
Fix expected type for return statements

### PR DESCRIPTION
**Pull request by datho7561**

### CODE REVIEW

**Comment by akurtakov** [comment]
This looks like something that should go in jdt.core and not being pushed to the fork.

**Comment by datho7561** [comment]
I think `ExpectedTypes.java` was added in our fork, I'll double check though

**Comment by datho7561** [comment]
Yes, this file was added in our fork.


This PR should fix 3 tests

**Comment by akurtakov** [comment]
How/where is it used? Changes to o.e.jdt.core should be upstreamed otherwise usage in eclipse suffers.

**Comment by akurtakov** [comment]
I don't mean my comment to be blocker for this PR but I expect the upstreaming to be taken with priority too.

**Comment by datho7561** [comment]
It's used in the DOMCompletionEngine.

Mickael wants to eventually upstream the DOMCompletionEngine, so that people using ECJ can use the DOMCompletionEngine. I don't think that the DOMCompletionEngine will ever work with ECJ, since ECJ does a poor job of recovering invalid content when building the AST. (There is a CompletionParser with additional hacks to recover more content for the CompletionEngine, but it's not used to build the AST). I've been working on the DOMCompletionEngine assuming javac will be used to generate the AST.

**Pull request merged**
