### PR TITLE
Enable completion tests

### PR DESCRIPTION
**Pull request by datho7561**
- Fix some low hanging completion test errors

### CODE REVIEW

**Comment by datho7561** [comment]
forgot to set the flag that enables DOM-based completion, so the tests are mostly passing :(

**Comment by datho7561** [comment]
There are less new failures than I expected, and there are ~8000 new tests whereas I was only expecting ~3000.

I'm going to try a few things to get it working properly

**Comment by datho7561** [comment]
I don't really know why there are so many new test runs. My belief is that the test suite is running twice: once in the  "check for regressions" run and once in the javac run. I'll take a look into excluding the javac tests in the regressions run

**Comment by mickaelistria** [comment]
Wasn't https://ci.eclipse.org/ls/job/jdt-core-incubator/job/PR-874/4/#showFailuresLink working as expected.
Indeed, we do run the tests twice, and it's intentional: once without Javac, one with Javac.
Maybe the CompletionTests were already executed twice but without the Javac flags?

**Comment by datho7561** [comment]
I can revert back to that state, I think that makes the most sense.

The o.e.j.c.tests.javac suite consists mainly of existing test suites configured to run properly for javac. It doesn't make sense to run them without javac, since those test suites are already being run as a part of a different test bundle (I think the o.e.j.c.tests.model bundle). I was trying to avoid running that test case in the first run to avoid this, but it seems like that causes test failures. I'll switch back to simply running the o.e.j.c.tests.javac suite both times.

**Comment by datho7561** [comment]
Current execution seems stuck :(

**Pull request merged**
