### PR TITLE
fix NPE due the jcVariableDecl.vartype being null

### PR DESCRIPTION
**Pull request by gayanper**

### CODE REVIEW

**Comment by gayanper** [comment]
@mickaelistria a small fix

**Comment by mickaelistria** [comment]
I had to rebase on top of latest JDT HEAD. Can you please rebase your commit?

**Comment by gayanper** [comment]
> I had to rebase on top of latest JDT HEAD. Can you please rebase your commit?

we might need to bump the versions of new module's parent to 4.33

**Comment by gayanper** [comment]
@mickaelistria once you fix the versions in javac modules and merge this PR, I will publish my other PR which improves the completions a bit more so it is usable like 50%

**Pull request merged**
