### PR TITLE
rebase to master & Adopt the new option to enable alternative compiler

### PR DESCRIPTION
**Pull request by testforstephen**
The switch for javac builder is changed to `-DAbstractImageBuilder.compilerFactory=org.eclipse.jdt.internal.javac.JavacCompilerFactory`

### CODE REVIEW

**Comment by mickaelistria** [comment]
Do you want me to `push --force` this branch to `dom-with-javac` or would you rather do it yourself?

**Comment by testforstephen** [comment]
oops, It looks like there is a new commit comes in dom-with-javac after my rebase. I have to rebase again. :)

**Comment by mickaelistria** [comment]
you can also just cherry-pick the latest commit onto your branch, it might be easier than rebasing

**Comment by testforstephen** [comment]
> you can also just cherry-pick the latest commit onto your branch, it might be easier than rebasing

cherry-picked, but it still has conflicts. Is there any way to force push to dom-with-javac branch using pull request?

**Comment by mickaelistria** [comment]
Those conflicts cannot be solved, they're because of change in intermediary commits. If the current state is good, we don't have to bother with those conflicts and we can just `push --force`. I don't think there is a way to do this with GitHub, but a good old `git push --force incubator HEAD:dom-with-javac` would do the trick.

**Comment by testforstephen** [comment]
> Those conflicts cannot be solved, they're because of change in intermediary commits. If the current state is good, we don't have to bother with those conflicts and we can just `push --force`. I don't think there is a way to do this with GitHub, but a good old `git push --force incubator HEAD:dom-with-javac` would do the trick.

thanks. I have force push it to dom-with-javac.

**Comment by mickaelistria** [comment]
Great, thank you!

**Pull request merged**
