### PR TITLE
Retrieve the annotation processing config from JDT project for use in Javac compiler

### PR DESCRIPTION
**Pull request by testforstephen**
This is the split PR based on discussion in https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/404.

### CODE REVIEW

**Comment by fbricon** [comment]
@testforstephen can you please rebase your PR?

**Comment by mickaelistria** [comment]
We're looking at contributing this upstream in JDT.
@testforstephen is it OK to wait a bit (~2 weeks) hoping this can be merged into JDT, or do you prefer it to be merged right now (at the risk of having to mitigate conflicts later)?

**Comment by testforstephen** [comment]
> We're looking at contributing this upstream in JDT. @testforstephen is it OK to wait a bit (~2 weeks) hoping this can be merged into JDT, or do you prefer it to be merged right now (at the risk of having to mitigate conflicts later)?

It's ok for me to hold on this PR and hopefully get the upstream jdt.core contribution point merged first.

**Comment by testforstephen** [comment]
@mickaelistria what approach do you use to sync dom-with-javac with master branch?

rebase it on master, and then fix conflicts?

**Comment by mickaelistria** [comment]
Yes, that's call `git pull --rebase eclipse master` is my usual approach. I've not found another better workflow so far. Luckily we rarely have conflicts, but I'm afraid you won't be that lucky... The good news is than in practice, we've only diverged by 2 commits on AbstractImageBuilder so far.

**Comment by mickaelistria** [comment]
@testforstephen Was this included in #509 ? If yes, can this be closed?

**Comment by testforstephen** [comment]
yes, the upstream PR has covered this. This is not needed any more.

**Pull request closed without merging**
