### PR TITLE
Fix test0008 and others: empty block comment misunderstood by javac a…

### PR DESCRIPTION
**Pull request by robstryker**
…s block comment

### CODE REVIEW

**Comment by mickaelistria** [comment]
This doesn't seem to fix test0008 (nor any other test) so far.

**Comment by robstryker** [comment]
It seems to fix it locally.  Will rebase and see if something is conflicting.

**Comment by robstryker** [comment]
```
< org.eclipse.jdt.core.tests.model.ClasspathTests testExtraAttributes4
827a827
> org.eclipse.jdt.core.tests.model.CompletionContextTests test0008
1310d1309
< org.eclipse.jdt.core.tests.model.CompletionTests18 test005
1317d1315
< org.eclipse.jdt.core.tests.model.CompletionTests18 test014
1375d1372
< org.eclipse.jdt.core.tests.model.CompletionTests18 test485492b
```

I'm assuming this is a problem with comparing to an active dom-with-javac branch, where someone else has fixed those 4 other tests. Those tests pass for me locally after rebasing.

**Comment by mickaelistria** [comment]
Fixes 2, let's merge.
About the diff, I recently faced a similar oddity and found out that the script to get failures needs to be updated to ignore the "FIXED" tests too:
```bash
curl -H 'Cache-Control: no-cache' --compressed https://ci.eclipse.org/ls/job/jdt-core-incubator/job/PR-1064/lastSuccessfulBuild/testReport/api/xml | xmllint --xpath '/testResult/suite/case[status != "PASSED" and status != "FIXED"]/*[name() = "className" or name() = "name"]/text()' - | sed 'N; s/\n/ /' - | sort > pr1064.txt
```

**Pull request merged**
