### PR TITLE
Parse multiple Patterns in a case statement

### PR DESCRIPTION
**Pull request by datho7561**
Second part of JEP 443.

- Change the parser so that it can parse a list of Patterns in a case.
- Change GuardedPattern AST (internal and and API) so that it has a list of patterns as its child instead of just one.
- Modify some tests that use record patterns with a variable (eg. `MyPoint(int x, int y) p` vs `MyPoint(int x, int y)`), since this syntax was only ever used in the preview version of the feature and is no longer allowed.
- Add code generation for all the above
- Include https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1816 to fix some bugs in code generation

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1742#issuecomment-1898498585 I nearly forgot that I still need to write the code for code generation.

**Comment by rgrunber** [comment]
Can you rebase this PR onto `develop` ? You don't need to carry "Releng changes for jdtls" as you would be requesting to be rebase on top of that & the JEP 445 PR.

**Comment by datho7561** [comment]
Please don't merge yet I still need to test it with JDT-LS

**Comment by datho7561** [comment]
I tried this class out, and it seems to be working as expected:

```java
public class MyClass {

	public static void main(String... args) {
		MyRecord<?> my_record = new MyRecord(null);

		switch (my_record) {
			case MyRecord(Chartreuse _), MyRecord(Licorice _):
				System.out.println("sweet");
				break;
			case MyRecord(Cilantro _):
				System.out.println("savory");
				break;
			default:
				System.out.println("yikes");
				break;
		}
	}
}


record MyRecord<T extends Flavour>(T f){}

sealed abstract class Flavour permits Cilantro, Licorice, Chartreuse {
}
final class Cilantro extends Flavour {}
final class Licorice extends Flavour {}
final class Chartreuse extends Flavour {}
```

I'll do another rebase.

**Comment by datho7561** [comment]
Pushing the rebase soon. I have the following 3 failures and 3 errors when running this change in the jdt.ls test suite:

```
Failures:
  ProjectUtilsTest.testGetMaxProjectProblemSeverity:51 expected:<0> but was:<2>
  ProtobufSupportTest.testGenerateProtobufSources:64
  GradleProjectImporterTest.testNameConflictProject:632 expected:<3> but was:<2>
Errors:
  ProtobufSupportTest.testAfterImportsForProtobuf:53 NullPointer Cannot invoke "java.util.List.size()" because "notifications" is null
  GradleProjectImporterTest.testProtoBufSupport:591 » JavaModel protobuf does not exist
  GradleProjectImporterTest.testProtoBufSupportChanged:609 » JavaModel protobuf does not exist
```

**Comment by datho7561** [comment]
@rgrunber FYI, one of the commits I include in this PR is a PR upstream, but that PR became stale due to changes in Pattern code generation, so I completely rewrote the upstream PR. https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2016

**Comment by datho7561** [comment]
We should use Srikanth's PR from upstream, which contains many bug fixes that Srikanth and I have written to this feature.

I'll open a PR here, so that if we want to include it in incubator, we can.

**Pull request closed without merging**
