### PR TITLE
Report "unused ..." diagnostics

### LINKED ISSUE #300: [javac] Report "unused ..." diagnostics
The javac compiler doesn't report "unused ..." diagnostics, but there's still a way to access that information, see how it's done in https://github.com/georgewfraser/java-language-server:  `com.sun.source.tree.CompilationUnitTree` is [scanned](https://github.com/georgewfraser/java-language-server/blob/ca503f1728594af4b77d68de0c04fd81d9dc10d1/src/main/java/org/javacs/markup/ErrorProvider.java#L49-L57) for unused local variables or fields in https://github.com/georgewfraser/java-language-server/blob/master/src/main/java/org/javacs/markup/WarnUnused.java

### PR DESCRIPTION
**Pull request by testforstephen**
Fixes #300

Report diagnostics for the unused import & private member (type/method/field) & local variable.

### CODE REVIEW

**Comment by testforstephen** [comment]
https://github.com/user-attachments/assets/bf086e6a-9c7c-4968-89ff-95ad891dea63

The quick fix for "remove unused type/variable/method" works, but "remove unused import" does not work. Looks like the DOM model for import has some issues.

```
!MESSAGE Internal Error
!STACK 1
org.eclipse.core.runtime.CoreException: The fix 'Remove unused import' generated a null change.
	at org.eclipse.jdt.internal.corext.fix.CompilationUnitRewriteOperationsFixCore.createChange(CompilationUnitRewriteOperationsFixCore.java:128)
	at org.eclipse.jdt.internal.ui.text.correction.proposals.FixCorrectionProposalCore.createTextChange(FixCorrectionProposalCore.java:97)
	at org.eclipse.jdt.core.manipulation.CUCorrectionProposalCore.createChange(CUCorrectionProposalCore.java:195)
	at org.eclipse.jdt.core.manipulation.ChangeCorrectionProposalCore.getChange(ChangeCorrectionProposalCore.java:153)
	at org.eclipse.jdt.core.manipulation.CUCorrectionProposalCore.getTextChange(CUCorrectionProposalCore.java:206)
	at org.eclipse.jdt.core.manipulation.CUCorrectionProposalCore.getAdditionalProposalInfo(CUCorrectionProposalCore.java:133)
	at org.eclipse.jdt.internal.ui.text.correction.proposals.FixCorrectionProposalCore.getAdditionalProposalInfo(FixCorrectionProposalCore.java:79)
	at org.eclipse.jdt.ui.text.java.correction.CUCorrectionProposal.getAdditionalProposalInfo(CUCorrectionProposal.java:191)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController$Timer$2$1.run(AdditionalInfoController.java:116)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.jdt.core.manipulation 4 0 2024-07-24 13:54:12.551
```

**Comment by datho7561** [comment]
I took a quick look over it and it seems pretty great!

From my testing, private static inner classes don't seem to be reported yet. eg.

```java
public class MyClass {
  // should be reported as unused
  private static class MyInnerStaticClass {

  }
}
```

Are you planning on looking into this for this PR? I think it's okay to leave it out for a future PR, just not sure if it's an oversight.

> Looks like the DOM model for import has some issues.

I've also been running into this; we should file this and look into it since it's also affecting completion in the import list.

**Comment by fbricon** [comment]
I just gave it a quick glance, but it seems to me that scanning is performed and then diagnostics are returned depending on the severity settings. I think scanning should be entirely skipped if all "unused" diagnostics are disabled/ignored in the settings

**Comment by mickaelistria** [comment]
As discussed in the call, I think this can be safely merged whenever you want.
There might be glitches or limitations or possible improvement, but already a lot of value that is better to be merged in ASAP.

**Comment by testforstephen** [comment]
> I took a quick look over it and it seems pretty great!
> 
> From my testing, private static inner classes don't seem to be reported yet. eg.
> 
> ```java
> public class MyClass {
>   // should be reported as unused
>   private static class MyInnerStaticClass {
> 
>   }
> }
> ```
> 
> Are you planning on looking into this for this PR? I think it's okay to leave it out for a future PR, just not sure if it's an oversight.

it works for me.
image


> > Looks like the DOM model for import has some issues.
> 
> I've also been running into this; we should file this and look into it since it's also affecting completion in the import list.

Will file an issue for this after the PR is merged.

**Comment by testforstephen** [comment]
> I just gave it a quick glance, but it seems to me that scanning is performed and then diagnostics are returned depending on the severity settings. I think scanning should be entirely skipped if all "unused" diagnostics are disabled/ignored in the settings

Yes, that's the current design, and I prefer to maintain it as is. If we later determine that skipping earlier is significantly beneficial, we can consider optimizing it then.

Since JDT enables warnings for unused imports and private members by default, and based on our past BI analysis, most users just use the default settings while only a few make changes.

**Comment by testforstephen** [comment]
I merge it first. If you find any bugs related to this feature, feel free to open issues and we can fix it with new pull request.

**Comment by datho7561** [comment]
I still can't get it working; I'll open a ticket

**Pull request merged**
