### PR TITLE
[DOM-first] Fix ASTModelBridgeTests test suite

### LINKED ISSUE #57: [DOM-first] Fix `ASTModelBridgeTests` test suite
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

### PR DESCRIPTION
**Pull request by snjeza**
Fixes #57 
Requires #101

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please submit as a dedicated PR the changes for DOMToModelPopulator? Those could be merged easily.
The other ones are less consensual and require more analysis:
We should really avoid changing existing tests in order to demonstrate real compatibilty, and forcing resolved statements is likely to break some cases.

**Comment by snjeza** [comment]
> Can you please submit as a dedicated PR the changes for DOMToModelPopulator? Those could be merged easily.
The other ones are less consensual and require more analysis:

~~I can.~~
@mickaelistria I have created #101 and updated this PR

> We should really avoid changing existing tests in order to demonstrate real compatibilty, and forcing resolved statements is likely to break some cases.

ASTModelBridgeTests  creates a working copy and doesn't destroy it between tests. I think that is not properly.
This change fixes testLocalVariable2 and testLocalVariable3. 
You can try to run only testLocalVariable2 or testLocalVariable3. It passes.

**Comment by mickaelistria** [comment]
The topic of recovery is a tricky one. I opened https://github.com/eclipse-jdt/eclipse.jdt.core/discussions/2130 and #119,  on this topic.
Let's close this PR and consider the recovery topic as a whole according to the discussion outcome.

**Comment by mickaelistria** [comment]
@snjeza I see you had to modify the test for some tests to pass, and I still see it seems necessary. I hope we can find a way to make those tests work without changing them. Do you think it would be possible?

**Comment by snjeza** [comment]
>  Do you think it would be possible?

I have tried but I didn't succeed
When running only testLocalVariable2 or testLocalVariable3, the test passes. ASTModelBridgeTests should discard the working copy.
Regarding testMethod10, JDT parser (SourceElementParser) set `setMethodsFullRecovery(true)`. ASTParser has no such method. I have used `astParser.setStatementsRecovery(true);`

**Comment by snjeza** [comment]
@mickaelistria testLocalVariable2 or testLocalVariable can be fixed using the following path:
```
diff --git a/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java b/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java
index f9a78b62aa..b86742f18f 100644
--- a/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java
+++ b/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java
@@ -776,7 +776,7 @@ private static boolean matchSignatures(IMethodBinding invocation, IMethodBinding
 
 
 private org.eclipse.jdt.core.dom.CompilationUnit getOrBuildAST(WorkingCopyOwner workingCopyOwner) {
-       if (this.ast == null) {
+       //if (this.ast == null) {
                ASTParser parser = ASTParser.newParser(AST.getJLSLatest()); // TODO use Java project info
                parser.setWorkingCopyOwner(workingCopyOwner);
                parser.setSource(this);
@@ -788,7 +788,7 @@ private org.eclipse.jdt.core.dom.CompilationUnit getOrBuildAST(WorkingCopyOwner
                if (parser.createAST(null) instanceof org.eclipse.jdt.core.dom.CompilationUnit newAST) {
                        this.ast = newAST;
                }
-       }
+       //}
        return this.ast;
 }
```

I can create a PR if you confirm it.

**Comment by snjeza** [comment]
>  I hope we can find a way to make those tests work without changing them. Do you think it would be possible?

@mickaelistria The following patch fixes all three failed tests:

```
diff --git a/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java b/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java
index f9a78b62aa..7ce63b98a3 100644
--- a/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java
+++ b/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/CompilationUnit.java
@@ -179,7 +179,7 @@ protected boolean buildStructure(OpenableElementInfo info, final IProgressMonito
                astParser.setWorkingCopyOwner(getOwner());
                astParser.setSource(this instanceof ClassFileWorkingCopy ? source : this);
                astParser.setProject(getJavaProject());
-               astParser.setStatementsRecovery((reconcileFlags & ICompilationUnit.ENABLE_STATEMENTS_RECOVERY) != 0);
+               astParser.setStatementsRecovery(true);
                astParser.setResolveBindings(computeProblems || resolveBindings);
                astParser.setBindingsRecovery((reconcileFlags & ICompilationUnit.ENABLE_BINDINGS_RECOVERY) != 0);
                astParser.setIgnoreMethodBodies((reconcileFlags & ICompilationUnit.IGNORE_METHOD_BODIES) != 0);
@@ -776,7 +776,7 @@ private static boolean matchSignatures(IMethodBinding invocation, IMethodBinding
 
 
 private org.eclipse.jdt.core.dom.CompilationUnit getOrBuildAST(WorkingCopyOwner workingCopyOwner) {
-       if (this.ast == null) {
+       if (this.ast == null || this.isWorkingCopy()) {
                ASTParser parser = ASTParser.newParser(AST.getJLSLatest()); // TODO use Java project info
                parser.setWorkingCopyOwner(workingCopyOwner);
                parser.setSource(this);

```
Do you want me to create a PR?

**Comment by mickaelistria** [comment]
The one about recovery fixes some tests in this suite but causes some other failures in other suites. So I suggest we skip it for the moment, or make it part of its own PR to see the actual impact on the whole test suite

The
```
-       if (this.ast == null) {
+       if (this.ast == null || this.isWorkingCopy()) {
```
change seems good and would be nice to have in a PR. I wish we can find some finer criteria to re-build ast or not (ie did the workingCopy get "dirty" since last call?). But please make a PR for it and we can discuss it with more focus, or decide to just merge it and potentially improve later.

**Comment by mickaelistria** [comment]
Actually, I had open https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/119 for the recovery stuff. I'll rebase it.

**Comment by snjeza** [comment]
> ... But please make a PR for it and we can discuss it with more focus, or decide to just merge it and potentially improve later.

@mickaelistria I have created https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/133

**Pull request closed without merging**
