### PR TITLE
Improve completion after dot

### PR DESCRIPTION
**Pull request by gayanper**
This PR is to handle various completion after dot like

```
Thread.//here
Thread.cu//here
Thread.currentThread().//
```

### CODE REVIEW

**Comment by gayanper** [comment]
@mickaelistria @testforstephen Please check and let me know if you see a way to handle these better.

I also found out if we have expression like 
`"hello" + name + " and " + ageValue.//here` where the `ageValue` is a variable, the node representing `ageValue` is identified as a TypeLiteral which is part of the InfixExpression. In this scenario we could try to extract the false type name and search for variables in current scope. But instead of variable if we have something like `System.` then we find a true TypeLiteral where the Type can be resolved. So we may need to handle these kind of different nodes. But I would like to find if we see another generic approach where we don't need to act on different false node because of the AST is not complete.

**Comment by gayanper** [comment]
@mickaelistria @testforstephen very much like to get your input on this strategy, i'm not really sure this is the best way to handle these cases.

**Comment by mickaelistria** [comment]
>  the node representing ageValue is identified as a TypeLiteral which is part of the InfixExpression. 

Is this with ECJ-based DOM, or with Javac? Do both underlying parser result in the same DOM? If not, we could identify some specific rules for mapping this case.

**Comment by robstryker** [comment]
> @mickaelistria @testforstephen Please check and let me know if you see a way to handle these better.
> 
> I also found out if we have expression like `"hello" + name + " and " + ageValue.//here` where the `ageValue` is a variable, the node representing `ageValue` is identified as a TypeLiteral which is part of the InfixExpression. In this scenario we could try to extract the false type name and search for variables in current scope. But instead of variable if we have something like `System.` then we find a true TypeLiteral where the Type can be resolved. So we may need to handle these kind of different nodes. But I would like to find if we see another generic approach where we don't need to act on different false node because of the AST is not complete.

When you find examples like this, it's best if we can try to figure out what the JDT implementation does with these trees, if possible, so that we know what we should aspire to. 

We do have one known issue with infix expressions ("a" + "b" + "c" should be represented as a single infix expression with left="a" and right="b" and additional=["c"]) but this clearly isn't what you're talking about here. Here you are talking about an incomplete / invalid file for completion purposes. 

Any time we have an invalid file, the odds that we do things the exact same way that jdt's existing implementation does is very low. In those situations it's best to figure out what the existing code is expecting and providing, and then see whether we can do that, perhaps with a test case. 

For now, I'd advise to "just make it work" to the best of our abilities and comment that the code block in question likely needs a better solution, and possibly even provide an example in the comments so that a motivated individual can add a test case at a later date. 

There are still so many test failures that parsing through them all is quite a challenge, so even new test cases are likely to get lost in the shuffle unless added to a dedicated test suite.

**Comment by gayanper** [comment]
> >  the node representing ageValue is identified as a TypeLiteral which is part of the InfixExpression. 
> 
> 
> 
> Is this with ECJ-based DOM, or with Javac? Do both underlying parser result in the same DOM? If not, we could identify some specific rules for mapping this case.

This is running with javac switch on and additionally adding the jvm property to enable dom base completion.

**Comment by gayanper** [comment]
I think we might need a approach similar to what can be seen here https://github.com/apache/netbeans/blob/643b64771c00c24d857773cd4d454c19f40bb57f/java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java#L1564

**Comment by gayanper** [comment]
@robstryker @mickaelistria if we were used to look at tokens that are near the current completions position to make a smart guess on where we are completing at like Netbeans implementation and also how JDT CompletionParser does, What Scanner implementation we should use ? 

If the idea behind DOMCompletionEngine is to make it possible to using even with ECJ. then I think we can make a Scanner abstraction and use javac Scanner for now, so ECJ scanner can be used later if it is needed.

**Comment by mickaelistria** [comment]
The final goal is to make it easier to adopt new Java versions in JDT, without having to wait for ECJ to include changes.
Usually, there are not so many changes in the Scanner, it's not the hardest bit to maintain. If we need to keep using ECJ scanner for this to work, I think we would still get a lot of benefits (the parser and the resolver are the bottlenecks in adoption of new Java constructs).
So at the moment, if you still need to use a Scanner, I think it's acceptable to use ECJ's one. We may consider a replacement later, but it can be that maintaining ECJ scanner is simpler on the long run than introducing some scanner abstractions. Time will tell and guide us.

**Comment by gayanper** [comment]
@mickaelistria isn't ECJ scanner is based on the grammar file that ECJ maintains, which means adapting to a new version will require to update the grammar and then adapt code. Not sure updating the grammar file will be sufficient and will not break any ECJ code in scenario where we want javac stuff to work. 

Thats the reason I thought of having a abstraction for scanner and translate to JDT tokens using Javac Scanner.

**Comment by mickaelistria** [comment]
>  isn't ECJ scanner is based on the grammar file that ECJ maintains

I don't think it is. It is mostly hand-written. I only uses the very minor bits generated by the grammar, such as TerminalTokens , but those are pretty stable across Java versions.

> Thats the reason I thought of having a abstraction for scanner and translate to JDT tokens using Javac Scanner.

I don't think it's a bad idea, however, I don't think it would be that simple either. That's why I would recommend sticking to something simpler that still would allow to consume newer Java without waiting much for JDT, and I think that sticking to ECJ scanner is good enough at the moment.

**Comment by gayanper** [comment]
@mickaelistria do we have any test base classes setup for start writing unit tests for DOMCompletionEngine ? Or are we planning to reuse current completion engine tests by passing the flags ?

**Comment by mickaelistria** [comment]
> do we have any test base classes setup for start writing unit tests for DOMCompletionEngine ?

No, but feel free to start one if you want.

> Or are we planning to reuse current completion engine tests by passing the flags ?

Ideally yes.

**Comment by gayanper** [comment]
I will try first using existing tests if possible with javac mode. If it is possible to get those tests reused somehow which I don't know yet. Then i can start adding functionality to make those tests pass.

**Comment by gayanper** [comment]
I think I now understand what @robstryker was suggesting, I think fixing some of the unsupported DOM conversions and fixing few errors while converting could actually help us to support more completions scenarios without needing to do token scanning. 

I will push some of those fixes tomorrow as a PR if they are not fixed by any of pending PR.

**Comment by mickaelistria** [comment]
@gayanper Do you think you could rebase your current code and we can then merge it as a profitable operation already?

**Comment by mickaelistria** [comment]
I've tried to cupture it all in https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/500 which I intend to merge as soon as test complete showing no regression with it.

**Comment by gayanper** [comment]
Sorry @mickaelistria i was away last 4 days on vacation. Sorry couldn't get back to you sooner. Let me known if anything needs to be done further

**Comment by mickaelistria** [comment]
I think it's all good and we can close.

> Let me known if anything needs to be done further

Further contributions would still be very welcome ;)

**Pull request closed without merging**
