### PR TITLE
Do not generate false positive unused parameter warning

### PR DESCRIPTION
**Pull request by akurtakov**
The following cases are fixed:
* Interface methods
* Abstract methods
* Methods marked with Override annotation

### CODE REVIEW

**Comment by datho7561** [comment]
The number of test failures increased by 30. I'll try to get the list of new failures (unfortunately this is a manual process so far).

**Comment by akurtakov** [comment]
> The number of test failures increased by 30. I'll try to get the list of new failures (unfortunately this is a manual process so far).

Interesting, do you see anything that might cause them in the PR itself?

**Comment by datho7561** [comment]
My initial guess was a null check missing somewhere. However it seems that there are some failures in CompletionTests18 that are listed twice. This doesn't make sense to me, but it could be the culprit.

**Comment by datho7561** [comment]
eg. `CompletionTests18.test492947b` is listed three times: twice as 'javac specific tests' and once as 'Build and Test'

**Comment by akurtakov** [comment]
I've rerun the build as I don't see any relation between what you pointed and the PR.

**Comment by akurtakov** [comment]
https://ci.eclipse.org/ls/job/jdt-core-incubator/job/PR-925/2/ has 1313 failing tests while head of dom-with-javac branch has 1312 tests https://ci.eclipse.org/ls/job/jdt-core-incubator/job/dom-with-javac/603/ . Aka failures are not caused by this patch.

**Comment by akurtakov** [comment]
Merging as per previous comment.

**Pull request merged**
