### PR TITLE
Fixes incubator #740 - ignore some specific malformed declarations

### PR DESCRIPTION
**Pull request by robstryker**

### CODE REVIEW

**Comment by mickaelistria** [comment]
I'm not sure we need a specific handling of this case: here, we ask for no recovery, but we have a malformed node (using the FAKE_IDENTIFIER, so we should probably remove it from its parent. Such a strategy would be valuable generally to handle the no recovery case.

Basically, I'm thinking of something in JavacCompilationUnitResolver.parse() that would be like
```java
if ((flag & ICompilationUnit.ENABLE_STATEMENTS_RECOVERY)) {
   dom.accept(new Visitor() {
      boolean visit(ASTNode node) {
        if (node.isMalformed()) {
          if (node.getLocationInParent() instanceof ChildListPropertyDescriptor) {
            ((Collection)node.getParent().get(node.getLocationInParent())).remove(node);
         } else if ((node.getLocationInParent() instanceof ChildPropertyDescriptor child && !child.isMandatory())||
            (node.getLocationInParent() instanceof SimplePropertyDescriptor child && !child.isMandatory())) {
           node.setStructuralProperty(node.getLocationInParent(), null);
          } 
        }
      }
   }
}
```
to trim from our recovered tree everything that seems incorrect in 1st place.
That would allow to focus on recovering at best in the converter (which is the usual case), but still allow case where recovery is not desired to progress by skipping some elements.

**Comment by robstryker** [comment]
I think you're going to have a very hard time doing that, leaving statement recovery to the UnitResolver rather than the Converter. 

In this case, you end up with an erroneous node, and then a field declaration node with a type but no name. Trying to "create" these two astnode objects, mark them both as malformed, and then later try to merge them into 1 node, is going to be very very difficult. 

First, the erroneous node won't be easily translated to anything that belongs on the tree. So you'll likely just skip it, leaving you with only a malformed field declaration. Having only this malformed field declaration, you won't realize why it's there. You lose the context that the user was attempt to add a package declaration there. 

The context is important, especially in cases where two nodes need to be combined into 1.

**Comment by mickaelistria** [comment]
> In this case, you end up with an erroneous node, and then a field declaration node with a type but no name. Trying to "create" these two astnode objects, mark them both as malformed, and then later try to merge them into 1 node, is going to be very very difficult.

I don't think we need to merge or combine nodes here, but instead just navigate up in the tree and remove the node from its parent, as if those nodes never had existed.
I'm suggesting that because the case for #740, my understanding is that what is expected without recovery is that we get a "working AST" as output where erroneous nodes are simply removed (instead of recovered). And it seems to me that if we properly annotated recovered/malformed nodes, we can relative easily trim them out of the AST after.

**Comment by robstryker** [comment]
Yes I understand your point. But I disagree with it. 

When traversing the JCTree, you will get an eronous node that you cannot create a DOM item for. You will ignore it, and not place it into the tree. 

You will then find a Field declaration that has a type (which doesn't exist) and no name. You may add this to the DOM tree and mark it as malformed. 

Later, if statement recovery is not enabled, you can trim the malformed field declaration node. Sure. 

But if statement recovery IS enabled, all you know is you have a type with no name. The source for this field declaration will start at the letter 'B'. You will no longer have the context of the previous token, "package", because it is not in the dom tree.  Therefore, you will not have the context to know how to recover. You certainly won't go checking previous tokens in the source that exist prior to the source range on this 'B' token, so you will completely lose the 'package' part.  Therefore, attempts at recovery will fail. 

In reality, the 'B' should be the name, not the type. And 'package' should be the type, which is obviously invalid. With these TWO pieces of information, you can determine that this is a misplaced package declaration. But with just the field declaration (type: B, name: unset), you will have no way at all to recognize this is a misplaced package declaration.

**Comment by mickaelistria** [comment]
My concern here, coming for the JDT-LS issue is not really how to recover or not from that case. It's really more generally that we need a way to get a "proper" DOM which prevents from having malformed content.
Having logic such as "matchPackageFieldDecl" is IMO overkill here: after all, why not letting things be recovered like Javac suggests? Whichever recovery is chosen for that case would anyway be wrong as long as `package` is still here. The goal is not to make things more or less wrong, but really to have a reliable way to generate a viable DOM when `enableStatementsRecovery` is disabled.

**Comment by robstryker** [comment]
`why not letting things be recovered like Javac suggests? `

Because the unit tests say often demand it be recovered a different way.

**Comment by mickaelistria** [comment]
This got merged as part of another PR.
Note that I'm trying the suggested alternative implementation which I believe is making things significantly simpler to maintain. If this is working, I will probably push a revert of that particular commit.

**Pull request closed without merging**
