### PR TITLE
Try should-stop.ifError Javac options when getting DOM

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
This does add some extra analysis (such as unused imports), so it's valuable; and we should aim at merging it. (cc @testforstephen @datho7561 as it might be a viable alternative to TolerantCompiler).
However, it does cause more tests to fail because Javac-based DOM is richer than ECJ-based one.  @robstryker How do you think we should proceed here? Is there an annotation in place for such case where "Javac is too good for this test" ?

**Comment by mickaelistria** [comment]
Here are the extra failures with this change
```
$ diff ok_1057.txt extraWarnings.txt 
82a83
> org.eclipse.jdt.core.tests.dom.ASTConverter15JLS4Test test0237
211a213
> org.eclipse.jdt.core.tests.dom.ASTConverter15JLS8Test test0237
340a343
> org.eclipse.jdt.core.tests.dom.ASTConverter15Test test0237
460a464
> org.eclipse.jdt.core.tests.dom.ASTConverterAST3Test test0261
478a483
> org.eclipse.jdt.core.tests.dom.ASTConverterAST4Test test0261
501a507
> org.eclipse.jdt.core.tests.dom.ASTConverterAST8Test test0261
727a734
> org.eclipse.jdt.core.tests.dom.ASTConverterTest2 test0438
734a742
> org.eclipse.jdt.core.tests.dom.ASTConverterTest2 test0477
738d745
< org.eclipse.jdt.core.tests.dom.ASTConverterTest2 test0489
767a775
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST3_2 test0438
774a783
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST3_2 test0477
778d786
< org.eclipse.jdt.core.tests.dom.ASTConverterTestAST3_2 test0489
833a842
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST3_2 test0667_2
858a868
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST4_2 test0438
865a876
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST4_2 test0477
869d879
< org.eclipse.jdt.core.tests.dom.ASTConverterTestAST4_2 test0489
924a935
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST4_2 test0667_2
946a958
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST8_2 test0438
953a966
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST8_2 test0477
957d969
< org.eclipse.jdt.core.tests.dom.ASTConverterTestAST8_2 test0489
1011a1024
> org.eclipse.jdt.core.tests.dom.ASTConverterTestAST8_2 test0667_2
1041a1055
> org.eclipse.jdt.core.tests.dom.ASTConverterTest test0261
1056a1071
> org.eclipse.jdt.core.tests.model.ClasspathTests test232816f
1057a1073
> org.eclipse.jdt.core.tests.model.ClasspathTests testDotDotLibraryEntry8
```
Many are caused by some assertion patterns such as `assertEquals(1, unit.getProblems().length)` which become invalid with that change as new extra problems (and interesting ones) are generated.
We discussed it with @robstryker and it seems like we shouldn't merge this PR if it breaks some tests as it will reduce the coverage and leave room for more bugs. The best possible strategy forward, when applicable, would be to submit a change upstream to make the test more lenient (eg replacing the count by just checking 1 particular problem exist). We'll try it as much as possible before merging this enhancement. In case some tests cannot be improved, we'll sadly annotate them so they get ignored with Javac and maybe copy them to the Javac-specific test bundle so a variation is run.

**Comment by testforstephen** [comment]
I'm curious why this issue arises only after enabling should-stop.ifError. Wasn't this a pre-existing issue, given that it's known Javac and ECJ generate different scales of problem lists?

How did we handle problem discrepancies before? Can we apply the same strategy to address this new case in the PR?

**Comment by mickaelistria** [comment]
> I'm curious why this issue arises only after enabling should-stop.ifError. 

Because without this setting, the parsing/resolution stops the process earlier and the extra analysis steps were skipped.

**Comment by mickaelistria** [comment]
One thing to try is to find a way to identify whether we're currently running JDT-Core tests. If we are, then we can skip the flag, and otherwise, turn it on.

**Comment by mickaelistria** [comment]
This got rebased and merged after adding a check to not alter test results.

**Pull request closed without merging**
