### PR TITLE
support annotation completions

### PR DESCRIPTION
**Pull request by gayanper**
- support annotation completion after '@'
- support annotation member completion excluding visible bindings
- code cleanup for unused methods

### CODE REVIEW

**Comment by gayanper** [comment]
@mickaelistria @datho7561 some improvements for the DOMCompletionEngine

**Comment by mickaelistria** [comment]
Just out of curiosity, do you use some strategy to prevent from regressions on this code? I'm currently only merging blindly (not even testing)

**Comment by gayanper** [comment]
> Just out of curiosity, do you use some strategy to prevent from regressions on this code? I'm currently only merging blindly (not even testing)

It's only local testing. But its not sufficient at all since I don't trust my self for testing all scenarios. 

If we fix access modifiers and relevance, could we rely on existing JDT tests ?

**Comment by mickaelistria** [comment]
As much as possible yes, running JDT tests with DOM-based completion is a goal, but I don't think it's an easy one to achieve. Or do you feel that that it is already close to be on par with legacy completion?

**Comment by gayanper** [comment]
@mickaelistria i will have a look if we can get some tests up and running. Ideally we can focus on what is been asserted with regards to completions. 

I will provide a update about my findings in coming days.

**Pull request merged**
