### PR TITLE
Flatten chains of InfixExpressions

### LINKED ISSUE #419: Chains of binary expressions with same operator should be converted with `InfixExpression.extendedOperands`
Looking at failing `ASTConverterTest.test108`, it looks like we should run an extra processing step that analyzes trees of InfixExpression to flatten them into a single InfixExpression with `extendedOperands` when the same operator is used.

### PR DESCRIPTION
**Pull request by mickaelistria**
Fixes https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/419

### CODE REVIEW

**Comment by mickaelistria** [comment]
That's annoying: test0106 verifies that in some case, the optimization doesn't happen.
I'm tempted to just ignore the test.

**Comment by datho7561** [comment]
@mickaelistria what are your thoughts on merging this? Overall to me, it seems it reduces the number of dom conversion test failures.

**Comment by mickaelistria** [comment]
I'll rebase and see, but the fact that it's causing other failures is an annoyance I'd like to understand and fix.

**Comment by robstryker** [comment]
Fixed by https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/497

**Pull request closed without merging**
