### PR TITLE
Support DCErroneous and create problem markers for it

### PR DESCRIPTION
**Pull request by akurtakov**
Storing the diagnostics as they appear and adding them at the end in one go so the top level CompilationUnit is already there.

### CODE REVIEW

**Comment by akurtakov** [comment]
image
This is nice extra error which JDT doesn't have and costed a lot of time to get javadocs clean.

**Comment by mickaelistria** [comment]
Cool addition, thanks!

**Comment by fbricon** [comment]
Can we at least turn it into a warning? It doesn't make much sense to report a copyright problem as an error

Screenshot 2024-05-17 at 12 09 17

lemminx compiles fine with javac BTW

**Comment by fbricon** [comment]
@angelozerr stop putting angle brackets in your headers ;-)

**Comment by akurtakov** [comment]
I'll make it warning . Honestly, I have no idea why it is reported as error and seems to be later ignored by javac.

**Comment by mickaelistria** [comment]
> I have no idea why it is reported as error and seems to be later ignored by javac.

`javac` usually ignores Javadoc comments and ignores the errors in Javadoc; but those are reported by the `javadoc` comment (which reuses `javac` parser and then crawls for extra javadoc erros to report). The reason why this is an error is that Javadoc allows a (sup/sub?)set of HTML and those are invalid HTML tags.

**Comment by akurtakov** [comment]
@fbricon Here you are https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/398

**Pull request merged**
